(() => {
'use strict';
const BANK = window.QUESTION_BANK || [];
const LECTURES = window.INFECT_LECTURES || [];
const CATEGORIES = [
 {id:'basics',name:'感染症の基礎',desc:'微生物の分類・細胞構造',icon:'◉',color:'#7de0d7',bg:'#1a3c45'},
 {id:'bacteria',name:'細菌学',desc:'Gram染色・代表的な起因菌',icon:'▦',color:'#85aaff',bg:'#253352'},
 {id:'antibiotics',name:'抗菌薬',desc:'作用機序・スペクトラム・耐性',icon:'✳',color:'#f7c785',bg:'#463b33'},
 {id:'viruses',name:'ウイルス',desc:'DNA / RNA・疾患・治療',icon:'⬡',color:'#d8b3ff',bg:'#39314e'},
 {id:'fungi',name:'真菌',desc:'カンジダ・アスペルギルスなど',icon:'♧',color:'#90d5ae',bg:'#233e37'},
 {id:'parasites',name:'原虫・寄生虫',desc:'生活環・感染経路・治療',icon:'◎',color:'#f4b2a5',bg:'#4b343b'},
 {id:'diagnostics',name:'検査・感染対策',desc:'培養・抗原抗体・隔離予防策',icon:'◇',color:'#95cce6',bg:'#263e50'},
 {id:'clinical',name:'臨床推論',desc:'疾患から起因菌・治療を考える',icon:'✚',color:'#d9c7ff',bg:'#3b3650'}
];
const KEYS = ['A','B','C','D'];
const STORAGE = 'infectlab-v1';
const app = document.getElementById('app');
let state = {route:'home', filters:{cat:'all',level:'all',status:'all'}, session:null};
function loadStore(){try {const d=JSON.parse(localStorage.getItem(STORAGE)); return d&&typeof d==='object'?{records:d.records||{},bookmarks:d.bookmarks||{}}:{records:{},bookmarks:{}}}catch{return {records:{},bookmarks:{}}}}
let store=loadStore();
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(store))}catch{notify('端末への保存に失敗しました')}}
function esc(s){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function catOf(id){return CATEGORIES.find(c=>c.id===id)||CATEGORIES[0]}
function lvl(q){return Number(q.level)||1}
function seen(q){return (store.records[q.id]?.seen||0)>0}
function wrong(q){return (store.records[q.id]?.wrong||0)>0}
function known(q){return store.records[q.id]?.lastCorrect===true}
function bookmarked(q){return !!store.bookmarks[q.id]}
function stat(){let viewed=0,correct=0,total=0,needs=0,mastered=0;for(const q of BANK){const r=store.records[q.id];if(!r)continue;if(r.seen)viewed++;correct+=r.correct||0;total+=r.seen||0;if((r.wrong||0)>0&&r.lastCorrect===false)needs++;if(r.lastCorrect)mastered++;}return {viewed,correct,total,needs,mastered,rate:total?Math.round(correct/total*100):0}}
function progressFor(cat){const a=BANK.filter(q=>q.category===cat),n=a.filter(seen).length;return {n,all:a.length,pct:a.length?Math.round(n/a.length*100):0}}
function shuffled(a){const t=[...a];for(let i=t.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[t[i],t[j]]=[t[j],t[i]]}return t}
function header(eyebrow,title,desc=''){return `<div class="eyebrow">${esc(eyebrow)}</div><h1 class="page-title">${esc(title)}</h1>${desc?`<p class="subhead">${esc(desc)}</p>`:''}`}
function metric(label,value,desc,symbol){return `<div class="metric"><span class="metric-symbol">${symbol}</span><div class="metric-label">${label}</div><div class="metric-value">${value}</div><small>${desc}</small></div>`}
function home(){let st=stat();return `<section class="hero"><div class="hero-content"><div class="eyebrow">YOUR INFECTION MEDICINE WORKSPACE</div><h1>感染症を、<br><span>「解ける知識」に。</span></h1><p>細菌・ウイルス・真菌・原虫・抗微生物薬。丸暗記じゃなく、分類と仕組みから体系的に。</p><button class="btn btn-primary" data-action="start" data-mode="beginner">基礎からスタート <span>→</span></button></div></section>
 <div class="stats-grid">${metric('問題数',BANK.length,'全8分野のオリジナル問題','▤')}${metric('学習済み',st.viewed,'一度でも解いた問題','◈')}${metric('累計正答率',st.rate+'%','全回答から計算','◎')}${metric('復習待ち',st.needs,'直近で間違えた問題','↺')}</div>
 <div class="section-head"><div><h2 class="section-title">分野別に学ぶ</h2><p class="subhead">気になる領域から選んでOK。初めてなら「感染症の基礎」へ。</p></div><button class="text-link" data-route="library">すべての問題 →</button></div><div class="cat-grid">${CATEGORIES.map(c=>{const x=progressFor(c.id);return `<button class="cat-card" data-action="category" data-cat="${c.id}"><div class="cat-top"><span class="cat-icon" style="--catbg:${c.bg};--catcol:${c.color}">${c.icon}</span><span class="cat-count">${x.all} QUESTIONS</span></div><div class="cat-name">${c.name}</div><div class="cat-desc">${c.desc}</div><div class="track"><span style="width:${x.pct}%"></span></div></button>`}).join('')}</div>
 <div class="quick-grid"><div class="panel"><span class="tag">QUICK PRACTICE</span><h3 style="margin-top:12px">10問チャレンジ</h3><p>全分野からランダムに10問。5分程度で知識をチェック。</p><div class="panel-actions"><button class="btn btn-primary btn-sm" data-action="start" data-mode="random10">ランダム10問 →</button><button class="btn btn-ghost btn-sm" data-action="start" data-mode="mistakes">復習だけ</button></div></div><div class="panel"><span class="tag alt">LEARN THE FRAMEWORK</span><h3 style="margin-top:12px">最初に理解したい整理表</h3><p>抗菌薬の標的、Gram染色、微生物の違いを1枚で整理。</p><button class="btn btn-ghost btn-sm" data-route="notes">まとめノートを見る →</button></div></div>`}
function filtered(){return BANK.filter(q=>(state.filters.cat==='all'||q.category===state.filters.cat)&&(state.filters.level==='all'||String(q.level)===state.filters.level)&&(state.filters.status==='all'||(state.filters.status==='unseen'&&!seen(q))||(state.filters.status==='wrong'&&store.records[q.id]?.lastCorrect===false)||(state.filters.status==='saved'&&bookmarked(q))))}
function library(){const fs=state.filters, qs=filtered();return `${header('QUESTION LIBRARY','問題ライブラリ','全分野から探して解ける。カテゴリ・難易度・学習状況で絞り込み。')}
<div class="filterbar"><select aria-label="分野で絞り込み" id="filter-cat"><option value="all">すべての分野</option>${CATEGORIES.map(c=>`<option value="${c.id}" ${fs.cat===c.id?'selected':''}>${c.name}</option>`).join('')}</select><select id="filter-level" aria-label="難易度で絞り込み"><option value="all">すべての難易度</option><option value="1" ${fs.level==='1'?'selected':''}>LEVEL 1 · 基礎</option><option value="2" ${fs.level==='2'?'selected':''}>LEVEL 2 · 応用</option><option value="3" ${fs.level==='3'?'selected':''}>LEVEL 3 · 臨床</option></select><select id="filter-status" aria-label="学習状況で絞り込み"><option value="all">すべての状況</option><option value="unseen" ${fs.status==='unseen'?'selected':''}>未学習</option><option value="wrong" ${fs.status==='wrong'?'selected':''}>直近で不正解</option><option value="saved" ${fs.status==='saved'?'selected':''}>ブックマーク</option></select><button class="btn btn-primary btn-sm" data-action="start" data-mode="filtered" ${qs.length?'':'disabled'}>絞り込んだ${qs.length}問を解く →</button></div>
<div class="detail-bar"><span class="muted" style="font-size:12px">${qs.length}問が見つかりました</span><span class="muted" style="font-size:11px">タップで1問からスタート</span></div><div class="question-list">${qs.length?qs.map(q=>`<button class="question-row" data-action="single" data-id="${q.id}"><span class="question-num">${esc(q.id)}</span><span class="question-row-main"><strong>${esc(q.question)}</strong><small>${catOf(q.category).name}　·　LEVEL ${q.level}${bookmarked(q)?'　·　★ 保存中':''}</small></span>${!seen(q)?'<span class="pill">未学習</span>':known(q)?'<span class="pill correct">正解</span>':'<span class="pill wrong">要復習</span>'}<span class="row-end">›</span></button>`).join(''):`<div class="empty"><strong>該当する問題はありません</strong>条件を変えるか、問題を解いて学習履歴を作ろう。</div>`}</div>`}
const NOTES=[
{title:'01. 微生物の5分類',html:'<table><tr><th>分類</th><th>特徴</th><th>治療の主役</th></tr><tr><td>細菌</td><td>原核生物。リボソーム70S・ペプチドグリカン細胞壁（原則）</td><td>抗菌薬</td></tr><tr><td>ウイルス</td><td>細胞構造・独立代謝を持たず、宿主細胞で増殖</td><td>抗ウイルス薬（一部）</td></tr><tr><td>真菌</td><td>真核生物。エルゴステロールを持つ細胞膜</td><td>抗真菌薬</td></tr><tr><td>原虫</td><td>単細胞の真核生物</td><td>抗原虫薬</td></tr><tr><td>蠕虫</td><td>多細胞の寄生虫</td><td>駆虫薬</td></tr></table>'},
{title:'02. Gram染色の考え方',html:'<p><b>陽性菌（紫）</b>：厚いペプチドグリカン層。ブドウ球菌・レンサ球菌など。<br><b>陰性菌（赤〜桃）</b>：薄い細胞壁＋外膜（LPS）。大腸菌・緑膿菌など。</p><p>Gram染色は薬剤選択の初手に有用。ただし菌種・薬剤耐性・感染部位で最終選択は変わる。</p>'},
{title:'03. 抗菌薬の作用点',html:'<table><tr><th>標的</th><th>代表</th></tr><tr><td>細胞壁（PBP）</td><td>βラクタム：ペニシリン、セフェム、カルバペネム</td></tr><tr><td>細胞壁（D-Ala-D-Ala）</td><td>バンコマイシン</td></tr><tr><td>細胞膜</td><td>ダプトマイシン、コリスチン</td></tr><tr><td>30S</td><td>アミノグリコシド、テトラサイクリン</td></tr><tr><td>50S</td><td>マクロライド、クリンダマイシン、リネゾリド</td></tr><tr><td>DNA複製</td><td>ニューキノロン</td></tr><tr><td>RNA合成</td><td>リファンピシン</td></tr><tr><td>葉酸代謝</td><td>ST合剤</td></tr></table>'},
{title:'04. βラクタム系の大枠',html:'<p><b>共通点</b>：PBP阻害で細胞壁合成を止める。時間依存性の殺菌作用が中心。</p><ul><li>ペニシリン系：薬剤ごとにスペクトラムが違う。アモキシシリンなど。</li><li>セフェム系：世代・個別薬剤でGram陽性/陰性カバーが異なる。</li><li>カルバペネム系：広域。ただしMRSAや非定型病原体を原則カバーしない。</li><li>モノバクタム系：アズトレオナムは好気性Gram陰性桿菌を中心にカバー。</li></ul>'},
{title:'05. 「効かない」の代表パターン',html:'<ul><li><b>マイコプラズマ</b>：細胞壁がない → βラクタム無効。</li><li><b>MRSA</b>：PBP2a（mecAなど） → 多くのβラクタムに耐性。</li><li><b>ESBL産生菌</b>：第3世代セフェムなどを加水分解。</li><li><b>嫌気性菌</b>：アミノグリコシドは酸素依存性取り込みが必要 → 原則無効。</li><li><b>緑膿菌</b>：薬剤による活性差が大きい。「広域＝緑膿菌に有効」ではない。</li></ul>'},
{title:'06. 抗微生物薬で押さえる副作用',html:'<table><tr><th>薬剤群</th><th>代表的な注意点</th></tr><tr><td>アミノグリコシド</td><td>腎毒性・耳毒性</td></tr><tr><td>バンコマイシン</td><td>腎毒性、急速投与時の注入反応</td></tr><tr><td>ニューキノロン</td><td>腱障害、QT延長（一部）、血糖異常など</td></tr><tr><td>テトラサイクリン</td><td>歯の着色・骨成長への影響、光線過敏</td></tr><tr><td>マクロライド</td><td>QT延長、薬物相互作用（一部）</td></tr><tr><td>アムホテリシンB</td><td>腎毒性、電解質異常</td></tr></table>'},
{title:'07. よく出る原虫・寄生虫',html:'<table><tr><th>病原体</th><th>感染のヒント</th></tr><tr><td>マラリア原虫</td><td>ハマダラカ、赤血球内寄生、発熱</td></tr><tr><td>赤痢アメーバ</td><td>血性下痢・肝膿瘍</td></tr><tr><td>ジアルジア</td><td>水系感染、脂肪便・吸収不良</td></tr><tr><td>トキソプラズマ</td><td>先天感染、免疫不全で脳病変</td></tr><tr><td>クリプトスポリジウム</td><td>水系感染、免疫不全で遷延性下痢</td></tr><tr><td>糞線虫</td><td>ステロイドなどで過剰感染に注意</td></tr></table>'},
{title:'08. 感染対策の原則',html:'<p><b>標準予防策</b>は全患者に行う。必要に応じて感染経路別予防策を追加する。</p><ul><li><b>空気</b>：結核、麻疹、水痘（接触予防策も必要）</li><li><b>飛沫</b>：百日咳、インフルエンザ（施設方針も確認）</li><li><b>接触</b>：C. difficile、疥癬など</li></ul><p>抗菌薬は「広ければ良い」ではない。検体採取・原因推定 → 初期治療 → 培養/感受性に応じた狭域化が大切。</p>'}
];
function notes(){return `${header('FRAMEWORK NOTES','まとめノート','暗記の前に、微生物と治療薬の全体地図を押さえよう。')}<div class="notes-grid">${NOTES.map(n=>`<article class="note"><h3>${n.title}</h3>${n.html}</article>`).join('')}</div><p class="session-note" style="margin-top:20px">※これは学習用の概略。例外、各薬剤の個別スペクトラム、耐性状況、薬物動態、患者背景によって治療は変わります。</p>`}
function progress(){let s=stat();return `${header('LEARNING ANALYTICS','学習データ','このブラウザでの学習履歴。別端末とは自動同期しません。')}<div class="stats-grid">${metric('学習済み',s.viewed+' / '+BANK.length,'問題を少なくとも1回回答','◈')}${metric('正答率',s.rate+'%','累計 '+s.total+' 回回答','◎')}${metric('理解済み',s.mastered,'直近の回答が正解','✓')}${metric('復習待ち',s.needs,'直近の回答が不正解','↺')}</div><div class="section-head"><h2 class="section-title">分野別の進捗</h2></div><div class="panel"><div class="progress-chart">${CATEGORIES.map(c=>{let p=progressFor(c.id);return `<div class="progress-line"><span>${c.name}</span><div class="track"><span style="width:${p.pct}%"></span></div><strong>${p.n}/${p.all}</strong></div>`}).join('')}</div><div class="panel-actions"><button class="btn btn-primary btn-sm" data-action="start" data-mode="mistakes">弱点を復習 →</button><button class="btn btn-ghost btn-sm" data-action="start" data-mode="saved">ブックマークを解く</button></div><div class="settings-box"><h3>学習データの管理</h3><p>回答履歴をJSON形式でバックアップできます。削除は取り消せません。</p><div class="panel-actions"><button class="btn btn-sm btn-ghost" data-action="export">記録を書き出す</button><button class="btn btn-sm btn-ghost" data-action="import">記録を読み込む</button><button class="btn btn-sm btn-ghost" data-action="reset">学習記録を初期化</button></div><input type="file" id="import-file" accept="application/json,.json" hidden></div></div>`}
function makeSession(questions, label,random=false){if(!questions.length){notify('対象の問題がまだありません');return}const q=random?shuffled(questions):[...questions];state.session={ids:q.map(x=>x.id),label,index:0,answers:{},correct:0};go('quiz')}
function start(mode,cat,id){if(mode==='beginner')return makeSession(BANK.filter(q=>q.category==='basics'&&q.level===1),'はじめての感染症');if(mode==='random10')return makeSession(shuffled(BANK).slice(0,Math.min(10,BANK.length)),'ランダム10問');if(mode==='mistakes')return makeSession(BANK.filter(q=>store.records[q.id]?.lastCorrect===false),'間違えた問題を復習',true);if(mode==='saved')return makeSession(BANK.filter(bookmarked),'ブックマーク復習',true);if(mode==='filtered')return makeSession(filtered(),'絞り込み演習');if(mode==='category')return makeSession(BANK.filter(q=>q.category===cat),catOf(cat).name+' 全問',false);if(mode==='single')return makeSession(BANK.filter(q=>q.id===id),'1問チャレンジ')}
function quiz(){const sess=state.session;if(!sess)return home();if(sess.index>=sess.ids.length)return finish();const q=BANK.find(x=>x.id===sess.ids[sess.index]);if(!q)return home();const selected=sess.answers[q.id];const answered=selected!==undefined;return `<div class="quiz-layout"><div class="quiz-top"><button class="back" data-action="leave">← 問題を終了する</button><span class="quiz-count">${esc(sess.label)}　${sess.index+1} / ${sess.ids.length}</span></div><div class="quiz-track"><span style="width:${((sess.index+1)/sess.ids.length)*100}%"></span></div><section class="quiz-card"><div class="question-labels"><span class="tag">${catOf(q.category).name}</span><span class="tag alt">LEVEL ${q.level}</span><span class="muted" style="font-size:11px">${q.id}</span></div><h2>${esc(q.question)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${answered&&i===q.answer?'correct':''} ${answered&&i===selected&&i!==q.answer?'incorrect':''}" data-action="answer" data-index="${i}" ${answered?'disabled':''}><span class="option-letter">${KEYS[i]}</span><span class="option-text">${esc(o)}</span>${answered&&i===q.answer?' ✓':answered&&i===selected?' ✕':''}</button>`).join('')}</div>${answered?`<div class="explain"><p class="explain-result ${selected===q.answer?'ok':'no'}">${selected===q.answer?'✓ 正解！':'✕ 惜しい、ここを整理しよう'}</p><p class="explain-intro">${esc(q.explanation)}</p><div class="reason-list">${q.reasons.map((r,i)=>`<div class="reason ${i===q.answer?'is-right':''}"><span class="reason-mark">${i===q.answer?'✓':'×'} ${KEYS[i]}</span><span>${esc(r)}</span></div>`).join('')}</div><div class="memory-box"><strong>📌 CHECK POINT</strong><br>${esc(q.point)}</div></div>`:''}<div class="quiz-actions"><button class="icon-btn ${bookmarked(q)?'saved':''}" data-action="bookmark" data-id="${q.id}">${bookmarked(q)?'★ 保存済み':'☆ あとで復習'}</button><button class="btn btn-primary" data-action="next" ${answered?'':'disabled'}>${sess.index+1===sess.ids.length?'結果を見る':'次の問題 →'}</button></div></section><p class="session-note" style="margin:14px 3px">${answered?'選択肢ごとの理由を確認しよう。':'回答は1〜4キーでも選べます。正誤と理由は回答後に表示。'}</p></div>`}
function finish(){const s=state.session;const n=s.ids.length;const rate=Math.round(s.correct/n*100);return `<div class="quiz-layout finish"><div class="finish-emoji">${rate>=80?'✳':rate>=50?'◈':'↺'}</div><span class="eyebrow">SESSION COMPLETE</span><h2>おつかれさま！</h2><p>${esc(s.label)} の結果。間違えたところは解説と一緒にもう一度。</p><div class="results">${metric('正解',s.correct+' / '+n,'今回のセッション','✓')}${metric('正答率',rate+'%','もう一歩ずつ積み上げよう','◎')}${metric('不正解',n-s.correct,'今回の要復習','↺')}</div><div class="panel-actions" style="justify-content:center"><button class="btn btn-primary" data-action="start" data-mode="mistakes">復習問題を解く →</button><button class="btn" data-route="home">ホームに戻る</button></div></div>`}
function answer(i){const s=state.session;if(!s||s.index>=s.ids.length)return;const q=BANK.find(x=>x.id===s.ids[s.index]);if(s.answers[q.id]!==undefined||i<0||i>3)return;s.answers[q.id]=i;const ok=i===q.answer;if(ok)s.correct++;const record=store.records[q.id]||{seen:0,correct:0,wrong:0};record.seen++;if(ok)record.correct++;else record.wrong++;record.lastCorrect=ok;record.lastAt=Date.now();store.records[q.id]=record;persist();render()}
function next(){const s=state.session;if(!s||s.index>=s.ids.length)return;const q=BANK.find(x=>x.id===s.ids[s.index]);if(s.answers[q.id]===undefined)return;s.index++;render();window.scrollTo({top:0,behavior:'instant'})}
function go(route){state.route=route;if(route==='home')state.session=null;render();window.scrollTo({top:0,behavior:'instant'})}
function render(){const pages={home:'ダッシュボード',library:'問題ライブラリ',notes:'まとめノート',progress:'学習データ',quiz:'クイズ'};document.getElementById('breadcrumb').textContent=pages[state.route]||pages.home;document.querySelectorAll('[data-route]').forEach(x=>{x.classList.toggle('active',x.dataset.route===state.route)});app.innerHTML=({home,library,notes,progress,quiz}[state.route]||home)()}
let timer;function notify(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),2800)}
function exportStore(){const data=JSON.stringify({version:1,exportedAt:new Date().toISOString(),records:store.records,bookmarks:store.bookmarks},null,2);const blob=new Blob([data],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='infect-lab-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importStore(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(data.version!==1||typeof data.records!=='object'||!data.records||typeof data.bookmarks!=='object'||!data.bookmarks)throw Error('形式');const ids=new Set(BANK.map(q=>q.id));const records={},bookmarks={};for(const [id,rec] of Object.entries(data.records)){if(!ids.has(id)||!rec||typeof rec!=='object')continue;const seen=Math.max(0,Number(rec.seen)||0),correct=Math.max(0,Number(rec.correct)||0),wrong=Math.max(0,Number(rec.wrong)||0);if(!Number.isFinite(seen+correct+wrong))continue;records[id]={seen:Math.min(seen,1000000),correct:Math.min(correct,seen),wrong:Math.min(wrong,seen),lastCorrect:rec.lastCorrect===true,lastAt:Number(rec.lastAt)||0}}for(const [id,value] of Object.entries(data.bookmarks)){if(ids.has(id)&&value===true)bookmarks[id]=true}if(!confirm('現在の学習記録を読み込んだ記録で上書きします。続けますか？'))return;store={records,bookmarks};persist();render();notify('学習記録を読み込みました')}catch{notify('読み込めないJSONファイルです')}};r.readAsText(file)}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-route],[data-action]');if(!btn)return;const route=btn.dataset.route,action=btn.dataset.action;if(route){e.preventDefault();go(route);return}if(action==='category')start('category',btn.dataset.cat);if(action==='start')start(btn.dataset.mode);if(action==='single')start('single',null,btn.dataset.id);if(action==='answer')answer(Number(btn.dataset.index));if(action==='next')next();if(action==='bookmark'){const id=btn.dataset.id;store.bookmarks[id]=!store.bookmarks[id];persist();render();notify(store.bookmarks[id]?'復習リストに保存しました':'保存を解除しました')}if(action==='leave')go('home');if(action==='export')exportStore();if(action==='import')document.getElementById('import-file')?.click();if(action==='reset'&&confirm('学習記録・ブックマークをすべて削除します。取り消せません。実行しますか？')){store={records:{},bookmarks:{}};persist();render();notify('記録を初期化しました')}});
document.addEventListener('change',e=>{const ids={'filter-cat':'cat','filter-level':'level','filter-status':'status'};if(ids[e.target.id]){state.filters[ids[e.target.id]]=e.target.value;render()}if(e.target.id==='import-file')importStore(e.target.files[0])});
document.addEventListener('keydown',e=>{if(state.route!=='quiz'||e.altKey||e.ctrlKey||e.metaKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['1','2','3','4'].includes(e.key)){answer(Number(e.key)-1)}else if(e.key==='Enter'&&state.session){const q=BANK.find(x=>x.id===state.session.ids[state.session.index]);if(q&&state.session.answers[q.id]!==undefined)next()}});
if(!BANK.length){app.innerHTML='<div class="empty"><strong>問題を読み込めませんでした</strong>questions.js の読み込みを確認してください。</div>'}else render();
})();
